### ISSUE TITLE
Stylesheet rules conflict with themes

### ISSUE THREAD

**Issue by CameronHall** [SynergyWholesale/WHMCS-Domains-Module#7]
The CSS rules used in the domains module are too generic and should be prefixed with `sw-` in order to avoid possible conflicts. 

For example, we have rules such as;
```css
.row input[type=text], .row select {
    height:33px
}

.loader {
...
}
```
